# square_helpers.py

# 🔒 Hardcoded Item → Category Mapping (from your Square export)
ITEM_CATEGORY_MAP = {
    "Biscoff": "Bingsu",
    "Biscoff Biscuit": "Extras & Toppings",
    "Biscoff Crown Croissant": "Uncategorized",
    "Biscoff Crumbs": "Extras & Toppings",
    "Biscoff Sauce": "Extras & Toppings",
    "Black Sesame": "Bingsu",
    "Black Sesame Latte": "Drinks",
    "Bubble Tea Mochi": "Extras & Toppings",
    "Cappuccino": "Drinks",
    "Chocolate": "Bingsu",
    "Chocolate Shokupan": "Shokupan",
    "Chocolate and Black Sesame - Day 2": "❄️ 12 Days of Xmas ❄️",
    "Coconut Brioche Bun": "Steamed Buns",
    "Coconut Jelly": "Extras & Toppings",
    "Coconut Pandan": "Bingsu",
    "Coconut Pandan Shokupan": "Shokupan",
    "Coffee Matcha Latte": "Drinks",
    "Condensed Milk": "Extras & Toppings",
    "Durian": "Bingsu",
    "Durian Puree": "Extras & Toppings",
    "Earl Grey Milk Tea": "Bingsu",
    "Espresso": "Drinks",
    "extra Matcha": "Extras & Toppings",
    "Flat White": "Drinks",
    "Fresh Strawberries": "Extras & Toppings",
    "Grass Jelly": "Extras & Toppings",
    "Hojicha": "Drinks",
    "Hojicha Latte": "Drinks",
    "Hot Chocolate": "Drinks",
    "Iced Black Sesame": "Drinks",
    "Iced Chocolate": "Drinks",
    "Iced Coffee Matcha": "Drinks",
    "Iced Hojicha": "Drinks",
    "Iced Latte": "Drinks",
    "Iced Long Black": "Drinks",
    "Iced Mango Milk": "Drinks",
    "Iced Matcha": "Drinks",
    "Iced Matcha Chocolate": "Drinks",
    "Iced Matcha Coconut": "Drinks",
    "Iced Matcha Mango": "Drinks",
    "Iced Matcha Mango and Iced Matcha Chocolate - Day 11": "❄️ 12 Days of Xmas ❄️",
    "Iced Matcha Strawberry": "Drinks",
    "Iced Mango Milk and Iced Strawberry Milk - Day 6": "❄️ 12 Days of Xmas ❄️",
    "Iced Strawberry Milk": "Drinks",
    "Key Chain": "Merchandise",
    "Latte": "Drinks",
    "Long Black": "Drinks",
    "Mango": "Bingsu",
    "Mango Cubes": "Extras & Toppings",
    "Mango Jelly": "Extras & Toppings",
    "Matcha": "Bingsu",
    "Matcha Crown Croissant": "Uncategorized",
    "Matcha Latte": "Drinks",
    "Matcha Mango Shokupan": "Shokupan",
    "Matcha Strawberry": "Bingsu",
    "Milo": "Bingsu",
    "Milo Cereal": "Extras & Toppings",
    "Mocha": "Drinks",
    "National Chocolate Caramel Day": "Uncategorized",
    "Oat Crumbs": "Extras & Toppings",
    "Oreo Crumbs": "Extras & Toppings",
    "Pandan Sauce": "Extras & Toppings",
    "Passion fruit": "Bingsu",
    "Passionfruit": "Bingsu",
    "Pearls": "Extras & Toppings",
    "Pistachio": "Bingsu",
    "Red Bean": "Extras & Toppings",
    "Shirt": "Merchandise",
    "Sticky Date Pudding": "Uncategorized",
    "Strawberry": "Bingsu",
    "Strawberry - Day 4": "❄️ 12 Days of Xmas ❄️",
    "Strawberry Bingsu + Iced Strawberry Milk": "❄️ 12 Days of Xmas ❄️",
    "Strawberry Mini Mochis": "Extras & Toppings",
    "T shirt": "Merchandise",
    "Thai Milk Tea": "Bingsu",
    "Tote Bag": "Merchandise",
    "Ube": "Bingsu",
    "Ube and Iced Chocolate - Day 1": "❄️ 12 Days of Xmas ❄️",
    "Whipped Cream": "Extras & Toppings",
    "White Pearls": "Extras & Toppings",
    "Yuzu Lychee": "Bingsu",
    "Yuzu Lychee (Vegan)": "Bingsu",
    "Coffee Tiramisu": "Bingsu",
    "T2 Teapot": "Drinks",
    "Mont Blanc": "Mont Blanc",
    "Strawberry Matcha": "Bingsu",
    "Iced Matcha Latte": "Drinks",
    "Iced Strawberry 🍓 Matcha": "Drinks",
    "Iced Hojicha Latte": "Drinks",
    "Lychee Popping Pearls": "Extras & Toppings",
    "Bing Hoodie": "Merchandise",
    "Hoodie": "Merchandise",
    "Iced Coffee Latte": "Drinks",
    "Bing Tees": "Merchandise",
    "T2 Sencha Tea": "Drinks",
    "Tira-Bingsu": "Bingsu",
    "White Peach Oolong": "Bingsu",
    "Yuzu Lychee (VG)": "Bingsu",
    "Matcha Coffee": "Drinks"
}

# You can import this into app.py:
# from square_helpers import ITEM_CATEGORY_MAP
